// apps/vue-app/src/components/Button.vue
<template>
    <button :class="StyledClass">
        <slot />
    </button>
</template>
  
<script lang="ts">
import { ButtonStyles, Colors } from 'ui'
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'Button',
    props: {
        color: {
            required: false,
            type: String,
            default: Colors.black
        }
    },

    computed: {
        StyledClass(): string {
            return `${ButtonStyles({ color: this.color })}`;
        },
    },
});
</script>

// apps/react-app/src/components/Button/Button.tsx
import { ButtonHTMLAttributes, forwardRef } from "react";
import { ButtonStyles, Colors } from "ui";

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  color?: string;
};
const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ color = Colors.black, children, ...props }, ref) => (
    <button
      ref={ref}
      type="button"
      className={ButtonStyles({ color })}
      {...props}
    >
      {children}
    </button>
  )
);

Button.displayName = "Button";

export { Button };
