// apps/react-app/src/components/Overlay/Overlay.tsx
import { Task } from "core";
import { ButtonHTMLAttributes, useEffect, useState } from "react";

type OverlayProps = ButtonHTMLAttributes<HTMLDivElement> & {
  clientCode: string;
  task: Task;
};

const Overlay = ({ clientCode, task }: OverlayProps) => {
  const isEditable = () => {
    if (clientCode !== task.clientCode) {
      const now = new Date();
      const differenceInSeconds =
        (now.getTime() - task.updatedAt.getTime()) / 1000;
      console.log(differenceInSeconds);
      return differenceInSeconds > 5;
    }
    return true;
  };
  const [time, setTime] = useState(Date.now());
  useEffect(() => {
    const interval = setInterval(() => setTime(Date.now()), 1000);
    return () => {
      clearInterval(interval);
    };
  }, []);
  return !isEditable() && <edit-overlay />;
};
Overlay.displayName = "Overlay";

export { Overlay };

// apps/vue-app/src/components/Overlay.vue
<template>
    <edit-overlay v-if="!isEditable" />
</template>
  
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'Overlay',
    props: {
        clientCode: {
            required: true,
            type: String,
        },
        task: {
            required: true,
            type: Object
        }
    },
    data() {
        return {
            interval: 0 as any,
            dateNow: new Date()
        };
    },

    computed: {
        isEditable(): boolean {
            if (this.clientCode !== this.task.clientCode) {
                const differenceInSeconds =
                    (this.dateNow.getTime() - this.task.updatedAt.getTime()) / 1000;
                return differenceInSeconds > 5;
            }
            return true;
        }
    },
    methods: {
        time() {
            this.dateNow = new Date()
        }
    },
    mounted() {
        this.interval = setInterval(() => this.time(), 100);
    },
    beforeDestroy() {
        clearInterval(this.interval);
    }
});
</script>
